---
title: Installing picozero offline
hero_image: images/banner.png
description: Installing picozero if you can't install through the Thonny package manager.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-22"
steps:
  - 
    title: Installing picozero offline
