---
title: Installerar picozero offline
hero_image: images/banner.png
description: Installerar picozero om du inte kan installera via Thonnys pakethanterare.
version: 4
listed: false
copyedit: false
last_tested: "2022-03-22"
steps:
  - 
    title: Installerar picozero offline
